colorListLegit = {'midnightblue', 'dimgrey', 'lavender', 'cadetblue', 'tan',
'mediumspringgreen', 'mistyrose', 'olivedrab', 'lightslategrey', 'paleturquoise',
 'cornflowerblue', 'darkslategray', 'mediumblue', 'honeydew', 'blue', 'linen',
 'darkviolet', 'royalblue', 'hotpink', 'white', 'peru', 'darkcyan', 'grey', 'ghostwhite',
  'lightgoldenrodyellow', 'slategrey', 'gray', 'snow', 'wheat', 'rosybrown',
  'lightgoldenrod', 'darksalmon', 'gold', 'forestgreen', 'yellowgreen',
  'indianred', 'lightyellow', 'violet', 'darkseagreen', 'mintcream',
  'seashell', 'deepskyblue', 'darkkhaki', 'chocolate', 'green', 'darkslateblue',
   'dodgerblue', 'mediumslateblue', 'darkblue', 'lightcyan', 'orange',
   'antiquewhite', 'firebrick', 'slateblue', 'oldlace', 'skyblue', 'lightgray',
   'yellow', 'goldenrod', 'darkgrey', 'navyblue', 'darkolivegreen', 'darkorchid',
   'pink', 'slategray', 'purple', 'darkmagenta', 'blueviolet', 'cyan',
   'blanchedalmond', 'lightslateblue', 'sienna', 'gainsboro', 'darkred',
   'navajowhite', 'darkgoldenrod', 'powderblue', 'salmon', 'turquoise',
   'mediumpurple', 'whitesmoke', 'lavenderblush', 'lightgrey', 'aquamarine',
   'seagreen', 'darkturquoise', 'lemonchiffon', 'limegreen', 'cornsilk',
   'floralwhite', 'sandybrown', 'maroon', 'darkgray', 'black', 'mediumorchid',
   'lightblue', 'lightgreen', 'mediumseagreen', 'aliceblue', 'papayawhip',
   'azure', 'orchid', 'bisque', 'deeppink', 'orangered', 'darkorange', 'beige',
   'darkslategrey', 'mediumvioletred', 'mediumturquoise', 'darkgreen', 'lightpink',
   'burlywood', 'magenta', 'lightslategray', 'tomato', 'greenyellow', 'lawngreen',
   'dimgray', 'ivory', 'peachpuff', 'palegreen', 'lightsteelblue', 'moccasin', 'khaki',
   'palevioletred', 'palegoldenrod', 'springgreen', 'saddlebrown', 'thistle',
   'lightseagreen', 'mediumaquamarine', 'lightskyblue', 'steelblue', 'coral',
   'navy', 'brown', 'lightcoral', 'lightsalmon', 'violetred', 'red', 'chartreuse', 'plum'}